CREATE TABLE USER (
  UserID INT PRIMARY KEY,
  UserName VARCHAR(255) NOT NULL,
  PW VARCHAR(255) NOT NULL
  TeamID INT,
  FOREIGN KEY (TeamID) REFERENCES TEAM(TeamID)
);

CREATE TABLE TEAM (
  TeamID INT PRIMARY KEY,
  TeamName VARCHAR(255) NOT NULL
);

CREATE TABLE TOKEN (
  TokenID INT PRIMARY KEY,
  TokenValue VARCHAR(255) NOT NULL,
  TokenType VARCHAR(255)
);

CREATE TABLE UserToToken (
  UserID INT,
  TokenID INT,
  FOREIGN KEY (UserID) REFERENCES USER(UserID),
  FOREIGN KEY (TokenID) REFERENCES TOKEN(TokenID),
  PRIMARY KEY (UserID, TokenID)
);
