version: '3.1'

services:
  mysql:
   image: mysql
   container_name: db-mysql
   ports:
    - 3307:3306
   environment:
     MYSQL_DATABASE: klayTrackerDatabase
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: testuser
     MYSQL_PASSWORD: pass
   volumes:
    - ./dump:/docker-entrypoint-initdb.d